---
title: "About"
---

::: {#hero-heading}
Ibnu Ariyanto is a lecturer and researcher at Universitas Indonesia.  Since March 2023, he has worked as a lecturer and researcher at the Master Program of Biomedical Science, Faculty of Medicine, Universitas Indonesia, in Jakarta.  (Department of Microbiology, FM UI).

He became interested in infectious immunology studies.   He is presently concentrating his study on cellular immunity to viral infections such as HIV and CMV.  He is eager to learn more about cellular therapy and future infectious disease treatment options.

He is presently employed with UKK PPM LMK (Lab services) as part of the Microbiology Department.  In January 2025, he was named as Person in Charge of the Serology Division, while simultaneously expanding Genomic Research and Services within the Molecular and Virology Divisions.

## Education

Doctor of Biomedical Science Universitas Indonesia

Master of Biomedical Science Universitas Indonesia

Bachelor Degree of Universitas Gaddjah Mada

## Laboratory

Department of Clinical Microbiology, Faculty of Medicine, Universitas Indonesia
:::
