---
title: "Research"
---

## Research Projects
## Ongoing

### CAR-NK Project

Initial development of artificial antigen-presenting cells (aAPC) for Natural killer cell expansion, the acceleration of the first CAR-NK cells in Indonesia
The project is a collaboration study with Prof. Alex Mc Lellan from the Department of Microbiology and Immunology at Otago University, New Zealand. I have gotten a small grant from DIPI to start the project in the Department of Clinical Microbiology, Faculty of Medicine, Universitas Indonesia. My supervisor from UI is dr. Rina la Distia Nora, Sp.M(K)., PhD & Fithriyah, PhD.
(https://dipi.id/awarded-proposal-dipis-small-research-grant-2024/). (ongoing)

### Immunology of HIV Patients

The collaborative research between Universitas Indonesia and Curtin University on Cytomegalovirus co-infection in HIV patients. We have discovered the role of several immune cells linked with clinical outcomes:

- CD4 and CD8 T-cells
- Natural killer cells
- Gamma Delta T cells (ongoing)

### Cytomegalovirus

The CMV research has been done in HIV patients starting ART, followed by 5 years in the JakCCANDO Study.

Currently working with Biomedical Science UI PhD student Isti Anindya to understand CMV's role in the cognitive development of Autism Spectrum Disorder (ASD) children (the principal investigator was Prof. Amin Subandrio). (ongoing)

We have been investigating CMV IL10 and human IL10R SNPs with Curtin/UWA Researcher Shelley Waters. The research also part of the Master Research of Yudha Fariska (master Student of Biomedical Science) (ongoing)

### Molecular Viability Assay of Mycobacterium lepra

I am co-supervisor of Clara Imaniar (master Student of Biomedical Science). The main supervisor is Prof Yeva Rosana (Dept. Microbiology FMUI). Our main goal is to develop a molecular method to identify live M. lepra from clinical samples. (ongoing)

## Finished

### COINCIDE Project (2024-2025)

I am participating in the COINCIDE Project. Working under the Prof. Anis Karuniawati Project, I am collaborating with Soe You Naing - Utrecht University. The project involves microbiology specialist student dr.Lili. (end on April)

### Vaccine Development (2021-2023)

I am working with a Master's student in biomedical science at the Faculty of Medicine (Raisha Muhayya), Universitas Indonesia. Her work is to develop recombinant SARS-CoV-2 vaccine construction. The vaccine design used a bioinformatic approach to predict the optimal epitope for T-cell response. (end)

### Infectious Diseases Molecular Diagnostics Development (2021-2022)

Work with a private company to validate qPCR kits (end)

## Journal Reviewer
I have participated in a peer review in :

Dovepress (Journal of Inflammation Research & Journal Infection and Drug Resistance)

Journal of Infection in Developing Countries (JIDC)

Acta Tropicana (Elsevier)

AIDS Research and Therapy (Springer Nature)

Critical Public Health (Taylor & Francis)

Frontiers Microbiology (Frontiers)

Human Immunology (Elsevier)


## Publication

### 2025

Anindya I, Sekartini R, Ariyanto IA, Wiguna T, Sari NP, Rahayu YS, et al. Cytomegalovirus-reactive IgG correlates with increased IL-6 and IL-1β levels, affecting eating behaviours and tactile sensitivity in children with autism. Biomedicines [Internet]. 2025 Feb 2 [cited 2025 Feb 2];13(2):338. Available from: https://www.mdpi.com/2227-9059/13/2/338
  


Ariyanto IA, Wijaya IP, Karim B, Lee S, Price P. Levels of Cytomegalovirus-reactive antibody and γδ T cell phenotypes align with vascular changes in people living with HIV. Viral Immunol [Internet]. 2025 Jan 2 [cited 2025 Jan 6]; Available from: https://www.liebertpub.com/doi/10.1089/vim.2024.0075
  


### 2024

Kartika AAA, Dewi BE, Ariyanto IA, Sudiro TM. Cassia alata butanol fraction anti-inflammatory effect on early expression of NFκB and cytokines in DENV-1 infected PBMCs. J Appl Pharm Sci [Internet]. 2024; Available from: https://scholar.google.com/citations?view_op=view_citation&hl=en&citation_for_view=X_K_5ewAAAAJ:JV2RwH3_ST0C



Ariyanto IA, Octaviana F, Wardah C, Beti E, Widyaningtyas S, Bela B, et al. Neuropathy among drug resistant HIV Patients treated in Jakarta. J Infect Dev Ctries [Internet]. 2024 Nov 30;18(11):1640–4. Available from: https://scholar.google.com/citations?view_op=view_citation&hl=en&citation_for_view=X_K_5ewAAAAJ:k_IJM867U9cC
  


Anindya I, Ariyanto IA, Soebandrio A. Prevalence of Cytomegalovirus Infection among Children with and with out Autism in Jakarta, Indonesia. Hosts Viruses [Internet]. 2024;11:94–100. Available from: https://researcherslinks.com/current-issues/Prevalence-of-Cytomegalovirus-Infection/6/1/10011/html
  


Amanah A, Ariyanto IA, Bela B, Primanagara R, Sudarmono P. Evaluation of the effect of mRNA and inactivated SARS-CoV-2 vaccines on the levels of cytokines IL-2, IFN-γ, and anti-RBD spike SARS-CoV-2 antibodies in people living with HIV (PLHIV). Biomedicines [Internet]. 2024 Sep 18 [cited 2024 Sep 20];12(9):2115. Available from: https://scholar.google.com/citations?view_op=view_citation&hl=en&citation_for_view=X_K_5ewAAAAJ:iH-uZ7U-co4C


Muhayya SR, Biomedical Sciences, Faculty of Medicine, Universitas Indonesia, Jl. Salemba Raya No. 6, Senen, Central Jakarta 10430, Jakarta, Indonesia, Ariyanto IA, Widianingtyas S, Subiantistha T, Bela B, et al. SARS-CoV-2 multi-epitope subunit vaccine proof-of-concept derived from the insilico study with protein expression in Escherichia coli BL21. Pharm J Indones [Internet]. 2024 Jun 30;9(2):71–8. Available from: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=X_K_5ewAAAAJ&sortby=pubdate&citation_for_view=X_K_5ewAAAAJ:r0BpntZqJG4C



Amanah A, Bela B, Widyaningtyas ST, Ariyanto IA, Sudarmono P. A review of the relationship between CD4 T-lymphocytes and efficacy of COVID-19 vaccines in people living with HIV (PLWH). In: THE 7TH BIOMEDICAL ENGINEERING’S RECENT PROGRESS IN BIOMATERIALS, DRUGS DEVELOPMENT, AND MEDICAL DEVICES: The 15th Asian Congress on Biotechnology in conjunction with the 7th International Symposium on Biomedical Engineering (ACB-ISBE 2022) [Internet]. AIP Publishing; 2024. Available from: https://pubs.aip.org/aip/acp/article-lookup/doi/10.1063/5.0200961



### 2023

Waters S, Allcock RJN, Lee S, Downing J, Ariyanto I, Leary S, et al. Do variations in the HLA-E ligand encoded by UL40 distinguish individuals susceptible to HCMV disease? Hum Immunol [Internet]. 2023 Feb;84(2):75–9. Available from: http://dx.doi.org/10.1016/j.humimm.2022.11.005




### 2022

Rahmawaty RG, Aziz MH, Dachwan C, Sari EY, Ariyanto IA, Wahid M. Challenges for Legionella pneumophila detection in Indonesia. JCMID [Internet]. 2022 Dec 25 [cited 2025 Jan 17];2(2):44–6. Available from: https://www.jcmid.id/index.php/JCMID/article/view/35
  
  

Ariyanto IA, Estiasari R, Lee S, Price P. Γδ T cell subpopulations associate with recovery of memory function in Indonesian HIV patients starting antiretroviral therapy. AIDS Res Hum Retroviruses [Internet]. 2022 Sep;38(9):764–70. Available from: http://dx.doi.org/10.1089/AID.2021.0171
  
  

Waters S, Lee S, Ariyanto I, Kresoje N, Leary S, Munyard K, et al. Sequencing of the viral UL111a gene directly from clinical specimens reveals variants of HCMV-encoded IL-10 that are associated with altered immune responses to HCMV. Int J Mol Sci [Internet]. 2022 Apr 22;23(9):4644. Available from: http://dx.doi.org/10.3390/ijms23094644
  


Ariyanto IA, Estiasari R, Karim B, Wijaya IP, Bela B, Soebandrio A, et al. Which NK cell populations mark the high burden of CMV present in all HIV patients beginning ART in Indonesia? AIDS Res Ther [Internet]. 2022 Mar 15;19(1):16. Available from: http://dx.doi.org/10.1186/s12981-022-00439-2
  


Waters S, Lee S, Ariyanto I, Leary S, Munyard K, Gaudieri S, et al. Variants of HCMV UL18 sequenced directly from clinical specimens associate with antibody and T-cell responses to HCMV. Int J Mol Sci [Internet]. 2022 Oct 26;23(21):12911. Available from: http://dx.doi.org/10.3390/ijms232112911
  


### 2021

Wijaya IP, Karim B, Azizi MS, Ariyanto I, Mansjoer A, Yunihastuti E, et al. Cytomegalovirus may influence vascular endothelial health in Indonesian HIV-infected patients after 5 years on ART. AIDS Res Ther [Internet]. 2021 Nov 11;18(1):83. Available from: http://dx.doi.org/10.1186/s12981-021-00410-7



Waters S, Agostino M, Lee S, Ariyanto I, Kresoje N, Leary S, et al. Sequencing directly from clinical specimens reveals genetic variations in HCMV-encoded chemokine receptor US28 that may influence antibody levels and interactions with human chemokines. Microbiol Spectr [Internet]. 2021 Oct 31;9(2):e0002021. Available from: http://dx.doi.org/10.1128/Spectrum.00020-21
  


Edwar L, Ariyanto IA, Tanudjaja SA, Sitompul R, Lee S, Price P. Interleukin-1A may illuminate differential effects of the retinal artery caliber in HIV patients. Mol Cell Biomed Sci [Internet]. 2021 Jul 6;5(2):88. Available from: https://cellbiopharm.com/ojs/index.php/MCBS/article/view/197
  

Edwar L, Ha P, Ariyanto IA, Estiasari R, Sitompul R, Lee S, et al. A TNF block genotype may influence CMV retinitis in HIV patients without affecting systemic viral replication. Curr HIV Res [Internet]. 2021;19(1):96–9. Available from: https://scholar.google.com/citations?view_op=view_citation&hl=en&citation_for_view=X_K_5ewAAAAJ:4DMP91E08xMC


Ariyanto IA, Lee S, Estiasari R, Edmands J, Bela B, Soebandrio A, et al. Understanding the effects of CMV on γδ T-cell populations in HIV patients starting antiretroviral therapy. Clin Immunol [Internet]. 2021 May;226(108696):108696. Available from: http://dx.doi.org/10.1016/j.clim.2021.108696



### 2020

Noviantari A, Rinendyaputri R, Ariyanto I. Differentiation ability of rat‐mesenchymal stem cells from bone marrow and adipose tissue to neurons and glial cells. Indones J Biotechnol [Internet]. 2020 Jun 26;25(1):43. Available from: https://scholar.google.com/citations?view_op=view_citation&hl=en&citation_for_view=X_K_5ewAAAAJ:aqlVkmm33-oC
  


Gaff J, Octaviana F, Pillay P, Mbenda HGN, Ariyanto IA, Gan JA, et al. TNF-block genotypes influence susceptibility to HIV-associated sensory neuropathy in Indonesians and South Africans. Int J Mol Sci [Internet]. 2020 Jan 7;21(2):380. Available from: https://scholar.google.com/citations?view_op=view_citation&hl=en&citation_for_view=X_K_5ewAAAAJ:ufrVoPGSRksC
  


Estiasari R, Aryanto I, Lee S, Pramana S, Djauzi S, Price P. Determinants of cognitive health in Indonesian HIV patients beginning antiretroviral therapy. J Neurovirol [Internet]. 2020 Feb;26(1):32–40. Available from: https://scholar.google.com/citations?view_op=view_citation&hl=en&citation_for_view=X_K_5ewAAAAJ:eQOLeE2rZwMC
  


Wulandari EAT, Wijaya IP, Karim B, Ariyanto I, Tanudjaja SA, Lee S, et al. Periodontitis and Cytomegalovirus associate with atherosclerosis among HIV patients after 5 years on ART. J Acquir Immune Defic Syndr [Internet]. 2020 Oct 1;85(2):195–200. Available from: https://scholar.google.com/citations?view_op=view_citation&hl=en&citation_for_view=X_K_5ewAAAAJ:qxL8FJ1GzNcC



### 2019

Ariyanto IA, Estiasari R, Edwar L, Makwana N, Lee S, Price P. Characterization of natural killer cells in HIV patients beginning therapy with a High burden of Cytomegalovirus. Immunol Invest [Internet]. 2019 May;48(4):345–54. Available from: https://scholar.google.com/citations?view_op=view_citation&hl=en&citation_for_view=X_K_5ewAAAAJ:Y0pCki6q_DkC
  


Edwar L, Karim B, Wijaya IP, Ariyanto I, Tanudjaja SA, Estiasari R, et al. Factors affecting the health of retinal vessels in human immunodeficiency virus patients beginning anti-Retroviral therapy. AIDS Res Hum Retroviruses [Internet]. 2019 Jun;35(6):529–35. Available from: https://scholar.google.com/citations?view_op=view_citation&hl=en&citation_for_view=X_K_5ewAAAAJ:W7OEmFMy1HYC
  


Gaff J, Octaviana F, Ariyanto I, Cherry C, Laws SM, Price P. Polymorphisms in CAMKK2 associate with susceptibility to sensory neuropathy in HIV patients treated without stavudine. J Neurovirol [Internet]. 2019 Dec;25(6):814–24. Available from: https://scholar.google.com/citations?view_op=view_citation&hl=en&citation_for_view=X_K_5ewAAAAJ:YsMSGLbcyi4C



### 2018

Waters S, Brook E, Lee S, Estiasari R, Ariyanto I, Price P. HIV patients, healthy aging and transplant recipients can reveal the hidden footprints of CMV. 2018 Feb 1;187:107–12. Available from: https://scholar.google.com/citations?view_op=view_citation&hl=en&citation_for_view=X_K_5ewAAAAJ:UeHWp8X0CEIC
  


Mountford J, Octaviana F, Estiasari R, Setiawan DD, Ariyanto I, Lee S, et al. Ex-vivo expression of chemokine receptors on cells surrounding cutaneous nerves in patients with HIV-associated sensory neuropathy. AIDS [Internet]. 2018 Feb 20;32(4):431–41. Available from: https://scholar.google.com/citations?view_op=view_citation&hl=en&citation_for_view=X_K_5ewAAAAJ:zYLM7Y9cAGgC
  


Ariyanto IA, Estiasari R, Waters S, Wulandari EAT, Fernandez S, Lee S, et al. Active and persistent Cytomegalovirus infections affect T cells in young adult HIV patients commencing antiretroviral therapy. Viral Immunol [Internet]. 2018 Apr 24;31(6):472–9. Available from: https://scholar.google.com/citations?view_op=view_citation&hl=en&citation_for_view=X_K_5ewAAAAJ:Tyk-4Ss8FVUC


### 2017

Dmello DM, Ariyanto I, Estiasari R, Halstrom S, Gaff J, Lee S, et al. Polymorphisms in IL10 may alter CD4 T-cell counts in Indonesian HIV patients beginning antiretroviral therapy. Hum Immunol [Internet]. 2017 Apr;78(4):387–90. Available from: https://scholar.google.com/citations?view_op=view_citation&hl=en&citation_for_view=X_K_5ewAAAAJ:u5HHmVD_uO8C
  


Karim B, Wijaya IP, Rahmaniyah R, Ariyanto I, Waters S, Estiasari R, et al. Factors affecting affect cardiovascular health in Indonesian HIV patients beginning ART. AIDS Res Ther [Internet]. 2017 Aug 31;14(1):52. Available from: https://scholar.google.com/citations?view_op=view_citation&hl=en&citation_for_view=X_K_5ewAAAAJ:2osOgNQ5qMEC
  
  
### 2013

Nuriliani A, Agus Ariyanto I, Ria Santi M, Mahendra A, Erly Sintya Dewi NW, Nurul Huda AL, et al. Aktivitas Sitotoksik dan Apoptosis Ekstrak Spons Spesies A Anggota Ordo Astroporida terhadap Sel HeLa (Cervical Cancer Cell Line). Biota : Jurnal Ilmiah Ilmu-Ilmu Hayati [Internet]. 2013 Feb 1;18(1):45–53. Available from: https://scholar.google.com/citations?view_op=view_citation&hl=en&citation_for_view=X_K_5ewAAAAJ:9yKSN-GCB0IC
  
